[theme]
base = "dark"
primaryColor = "#A259FF"
backgroundColor = "#0E0E16"
secondaryBackgroundColor = "#1A1A27"
textColor = "#F3F0FF"
font = "cambria"

[server]
runOnSave = true
headless = true
port = 8501


[browser]
gatherUsageStats = true